### ISSUE TITLE
Decide input to output mappings for ENC

### ISSUE THREAD

**Issue by maany** [simple-framework/simple_grid_puppet_enc#1]
Input = name of the puppet agent node
Output = roles in the puppet environment that need to be deployed on the puppet agent node.

If input node is puppetmaster, role to be applied is role::master
For nodes on which component repositories should be deployed, role to be applied is role::lightweight_component

**Comment by esilvaju** [comment]
Will be
```
---
classes:
role::lightweight_component:
id:
    - 1
    - 3
```
PS: Indentation matters
